### ISSUE TITLE
Design concerns

### ISSUE THREAD

**Issue by Lewiscowles1986** [djrobstep/migra#1]
Because you don't lock the database as far as I can see, your semi-automated solution will take far longer to complete.

https://github.com/djrobstep/migra/search?utf8=%E2%9C%93&q=lock

Worse still the only place I could find the rename command / keyword was in a test, where it renamed a column.

https://github.com/djrobstep/migra/search?utf8=%E2%9C%93&q=rename

My high-level overview of a schema migration would be

 * Take a backup (may be faster if tables are locked, but not all methods need this)
 * Create new table(s) with the structure required
 * Move data into the new table
 * Run tests on data-integrity
 * Administrator approves or rejects migration
 * If approved drop or rename the original table(s) and rename the new table(s)

Of course there are more complications and I try to avoid migrations altogether now, but it seems a safer alternative in case of error

**Comment by djrobstep** [comment]
Appreciate the comments. 

This is a diff tool, and a tool to *assist* in generating the SQL needed for migration scripts. Things like renames of tables/columns will always require manual intervention because a tool like this can't tell the difference between a rename vs a drop-and-create.

And it's certainly not designed to produce a fully complete script you can run without consideration to locking, testing, backups, and other things you mention that need to be considered when migrating a production database. 

I've attempted to make all this clear in the readme, but perhaps some further admonishment would be helpful.

**Comment by Lewiscowles1986** [comment]
In that case, would it be possible to allow it to generate a new table and SELECT in data from the destination table rather than altering an existing table? (this is where most of the risk comes from)

**Comment by djrobstep** [comment]
Definitely could be supported as an option. ``--copy-not-alter`` as a argument to the command or something?

**Comment by Lewiscowles1986** [comment]
Sure thing :smile:. It could even miss out the name of the DB to run the script on, relying on the user issuing a `USE` command if it is designed to be manual, then your program is kept simple / simplified releasing responsibility for the migration to a trusted third party. I think I'll have to use it before I continue down this path of suggestions, see if I can put something together and submit a PR. Sound like a plan?

**Comment by djrobstep** [comment]
Sounds awesome! Don't hesitate to hit me up if you need my opinion or clarification on anything.
