### ISSUE TITLE
Diff a schema and a database, not two databases

### ISSUE THREAD

**Issue by Bilge** [djrobstep/migra#100]
Hi, I've read your talk and the migra docs and I like the idea. However, I'm suffering some severe cognitive dissonance caused by the gap between what you claim should be possible and what seems to be documented as possible. Specifically, you claim we can have schemas as code and then migrate the production database to match that schema. But what actually seems to be happening is you can just diff live databases (where, presumably, one is development and one is production). Doesn't this defeat the whole point of schema in the VCS? It's no good to just generate a schema from a diff of databases, I need to generate a diff of a _shema file_ and a database, but all the docs show is examples of connecting to two live data sources and never reading any existing schema files. Am I missing something?

**Comment by djrobstep** [comment]
Yes to compare to a schema file, there are a couple of extra steps required, which is to create a temporary database and load the schema file into it.

There is an [example of this in the docs](https://djrobstep.com/docs/migra/dev-usage). In the `load_from_app` method you'd load your schema file.

I'd like to include this functionality directly into `migra` but it's somewhat tricky because not everybody wants to create temporary databases the same way, and I want to keep the tool focused on being a comparison tool rather than database management tool.

I did incorporate similar functionality over in [`results`](https://github.com/australianunions/results), another package I wrote. In the readme you'll see a `db.sync_db_structure_to_definition(statements)` which syncs a schema to a definition, perhaps that's what you want. Under the hood this uses the same `temporary_database` method from the docs, which relies on you having postgres running locally and connectable locally without a password.

Hope that helps!

**Comment by Bilge** [comment]
Oh wow. Seems a bit hacky. Is there never going to be any support for diffing DDL directly?

**Comment by djrobstep** [comment]
There will certainly never be a solution that doesn't involve loading the DDL statements into a postgres database - that would be way more hacky, because the best Postgres DDL parser is always going to be postgres itself.

The temporary database thing works pretty robustly - creating and dropping happens invisibly and takes very little time.

**Comment by Bilge** [comment]
What do you mean by *invisible?* If the tool provides no direct support for creating and tearing down temporary databases, and instead, you have to code that part yourself, it seems anything but invisible to me. In any case, the documentation could probably be clearer on this intended use case.

**Comment by djrobstep** [comment]
You do not have to code it yourself - it's a context manager that you import. See the example. 

Or if you use `results` you don't even have to import `temporary_database`.

**Comment by Bilge** [comment]
I don't know what that means, exactly, but it sounds like you think I code in Python, which is not the case. I intend to use this tool exclusively from the command-line as an external application.

**Comment by djrobstep** [comment]
Sounds like a great opportunity to learn some python - as I say, most of the functionality you need is easily importable into a script.

The command is not intended to cater for every possible workflow you might have, as noted in the docs:

> Every project is slightly different, so Migra doesn't try and solve every migration workflow problem you could possibly have. Instead, migra tries to make it as easy as possible to write scripts to solve your own migration problems.

**Comment by bikeshedder** [comment]
I just released [Tusker 0.2.0](https://pypi.org/project/tusker/0.2.0/) which supports this use case. It uses `migra` for all the diffing but provides an alternative user interface.
