### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by donbeave** [djrobstep/migra#122]
Hello, @djrobstep!

I'm a big fan of this project. I love it a lot. I think it's the best tool for doing PostgreSQL diff.

But the latest version has some lack of features and some bugs. And what's interesting most of these already fixed and available in PR.

Is this project is not active in maintaining anymore? If yes, maybe I and my team can help with providing some hands to merge these PRs and fix?

Best regards,
  Alexey Zhokhov.

**Comment by djrobstep** [comment]
Hello, thanks for asking, a valid question.

While there are many PRs waiting to be merged, a lot of them don't have any tests. I cannot merge code that is untested.

Reviewing and merging tested code is quick and something I can probably make time for fairly easily. But I don't have a lot of spare time for adding tests and fixing up PRs that are untested or otherwise need work.

Remember that this project is 100% a spare time exercise. I don't get to work on it as part of my job, and don't receive any financial support for it whatsoever.

Honestly, I'm somewhat jaded by the whole experience of people using happily using migra to make them/their employers job easier/make more money but not contributing back financially or in some other way. I don't feel much of a duty to bust my guts to fix these things if people aren't going to give back: I already have a full time job, a family, and several other projects. I'd love to be able to spend a lot more time on migra but financially, I cannot.

Here's a couple of suggestions for moving forward:

- I'm going to institute some hard rules for PRs going forward. A hard line limit, test coverage requirements etc. That will make it much easier to get things merged fast and regularly.
- Financial support. If you/your employer uses migra commercially, and it helps you substantially, please consider asking management to do some level of sponsorship, or a paid support arrangement (email me to discuss further).

**Comment by r-k-b** [comment]
Would adding a [GitHub Sponsors](https://github.com/sponsors) button make it easier for individuals to support your work? Or would you prefer to only ask commercial users?

**Comment by gregplaysguitar** [comment]
Hi @djrobstep , I'd like to email you regarding a possible commercial arrangement with my employer. Where would I find your email address? :)

**Comment by djrobstep** [comment]
@gregplaysguitar Cool, I'm at robertlechte at gmail
