### ISSUE TITLE
Multiple schema support?

### ISSUE THREAD

**Issue by kevboh** [djrobstep/migra#136]
Hello,

We're looking into using `migra` as a way to no longer write migrations and instead treat our SQL as genuine application code. However, we've split our SQL across multiple postgres schemas that relate to and depend on each other. I haven't dug much into the code, and am not a particularly good Python dev—is adding support for diffing multiple schemas as simple as allowing repeated `--schema` flags and updating `Migration` to accept an array of schemas, with the attendant changes that implies? Or is the idea of a schema built into diffing on a more fundamental level?

If the former, I'd be happy to take a shot at a PR. Thanks.

**Comment by djrobstep** [comment]
I'm not 100% sure if what you're looking for, but `migra` works on the level of the database, treating each schema separately.

So a table with the same name in a different schema is treated as an entirely separate thing.

You can use the schema flag already to compare two schemas of the same name in different databases. Comparing two schemas of different names is harder, because a lot of the code relies on equality comparisons where the schema name is compared as part of this.

It's a limitation of python objects and OO in general that you can only really define one kind of equality for an object. This example and many other real world examples are good demonstrations that there can be multiple types of equality. 

Changing to code to support such comparisons is possible, and desirable, but a little bit tricky. 

You've either got do get the objects from each schema and rename them temporarily within the inspection object on both sides to the same schema, for comparison purposes. Or reengineer the whole codebase to allow multiple types of comparison, this is less hacky but much more involved.

I think the temporary renaming trick would work fine, as I think the latter option is a much more long term re-engineering thing.

Is this what you're trying to do? Let me know if I've misunderstood. Or if not, happy to advise on putting together a PR for this.

**Comment by kevboh** [comment]
Sorry, I wasn't clear. Let me use an example:

```
create schema public_schema;
create schema private_schema;

create table public_schema.some_table (
    a_column text
);

create table private_schema.some_other_table (
    a_column_fkey text references public_schema.some_table(a_column) on delete cascade
    other text
);
```

My question is how to get both `public_schema` and `private_schema` reflected in what migra can generate. This pattern of using multiple pg schemas is common in tools such as [Postgraphile](https://www.graphile.org/postgraphile/).

**Comment by djrobstep** [comment]
Hey, I'm still not sure I understand. What in particular isn't supported in the public_schema/private_schema example?

**Comment by kevboh** [comment]
As far as I can tell, migra can only inspect a single postgres schema at a time. So I could get `public_schema.some_table` or `private_schema.some_other_table`, but not both. Is that correct?

**Comment by djrobstep** [comment]
Ah, you have run into a common source of confusion because the word schema has two different meanings - in general database parlance, schema means the structure of the whole database. But in Postgres, a schema means a namespace within a database that itself contains various database structures.

Migra uses the former meaning, and compares the whole schema (meaning 1) by default, which may contain several Postgres schemas (meaning 2), but also takes a flag to limit the output to a single schema (meaning 2).

It's certainly frustrating dealing with this ambiguity. For this reason I've started to say "structure" rather than schema for meaning 1, but this is not yet reflected in much of the docs.

Hope that clarifies things!

**Comment by kevboh** [comment]
Okay, so just to confirm—there is no way to limit migra to a set of postgres _namespaces_ (`schema` in DDL-speak), only either the entire contents of a database or a single postgres `schema`.

For what it's worth, I don't think I was confused; throughout this thread I have only ever used `schema` to mean a literal `create schema` result in Postgres...I never use schema to mean the alternative, as it is, as we discovered here, very misleading.

**Comment by djrobstep** [comment]
Not suggesting your usage is inconsistent, but just pointing out that the meaning often used in the docs (eg: migra: Like diff but for Postgres schemas) is different.

And yes, you can't do multiple postgres `schema`s in one go (of course, you can run several comparisons that compare one schema at a time, to accomplish the same thing). 

Supporting multiple specified schemas on the command line with the schema flag, comma-separated, would be a fairly straightforward change. Is this the PR you were thinking of making?

**Comment by kevboh** [comment]
I'm not sure if running several compares one at a time would be the same—wouldn't it fail if a given change to the `public` schema references the `private` schema, and then later public schema changes rely on that change? One would also have to solve ordering issues when merging the results.

**Comment by djrobstep** [comment]
Yes, you'll run into trouble if there are complex dependencies between schemas.

Even the existing single schema approach has limitations - to compare schemas it inspects the whole of each database, but then returns only the objects belonging to that schema - again this won't handle dependencies well and no doubt breaks in certain scenarios.

What's your actual use case here? Another approach that might fit better is an exclude feature - if for instance you want to compare most schemas but exclude some output.
