### ISSUE TITLE
CockroachDB compatible?

### ISSUE THREAD

**Issue by tobiasmuehl** [djrobstep/migra#164]
Has anyone tried if migra works with CockroachDB?

**Comment by djrobstep** [comment]
I've never tried. If you do, it would be interesting to hear how it goes.

**Comment by tobiasmuehl** [comment]
Ok, will have a play and let you know

**Comment by maximsmol** [comment]
Cockroach should be *sort of* compatible because they are compatible with the Postgres wire protocol. That being said, they are missing a bunch of features like triggers and row-level access control which migra supports. Now that shouldn't really get in the way of doing the actual migrations but might break the introspection code assuming it uses system catalogs for these features.

Feel free to open a new issue if you find any specific incompatibilities or comment here to confirm that it worked for you, but I'm closing this one as stale
