### ISSUE TITLE
Error when add column and not null constraint

### ISSUE THREAD

**Issue by x1g1** [djrobstep/migra#214]
When trying to run first time migra I got a lot of these type of errors.
Is there any workaround?

```
alter table "my_table" add column "my_field" character varying not null;
ERROR:  column "my_field" of relation "my_table" contains null values
```

if not could be replaced by:
```
alter table "public"."my_table" add column "my_field" character varying;
update "public"."my_table" set my_field = false where my_field is null;
alter table "public"."my_table" alter column "my_field" set not null;
```

**Comment by djrobstep** [comment]
Hey, thanks for filing this. Unfortunately it's beyond the scope of migra to make changes like this - migra can tell you how your schema needs to change, but can't tell you how you need to change your data in order to make that possible.

In your example, it's impossible for migra to know what to set nulls to appropriately - in your example, the field gets set to the string `'false'`, which is almost certainly not how most users would want to handle `null`s. 

It's best to write your own query to fix up such data issues before applying your migration/schema changes.
