### ISSUE TITLE
Left-to-right arguments

### ISSUE THREAD

**Issue by vassilevsky** [djrobstep/migra#5]
Hi 👻

I remembered that there was one thing I got wrong the first time I ran `migra`: the order of databases.

I expected that the program will generate SQL "from first to second" database. I mean, the SQL needed to make the second database look like the first one.

I got the "inverse" SQL the first time. Then I switched the arguments and got the correct one.

Perhaps it would be better to swap the arguments?

Or introduce named arguments like `--reference` and `--target`?

**Comment by djrobstep** [comment]
> I expected that the program will generate SQL "from first to second" database. I mean, the SQL needed to make the second database look like the first one.

Hmm, not sure I follow. I chose the current order to be consistent with the diff command and traditional patch files, for example: 

`> diff -n A.txt B.txt`

will output a patch that you apply to A in order to make it match B. 

Likewise, migra generates SQL that you apply to database A to make it match database B.

**Comment by vassilevsky** [comment]
IDK why but I kinda thought that it works "left to right" 🙃

**Comment by djrobstep** [comment]
I realize everybody's subjective intuition is different :) But to me it intuitively makes sense left to right when thought of as: from -> to, old -> new, etc.

I'm hesitant about adding named arguments because I think it's better to enforce a single correct way to run the command.
